spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/spring_batch
    username: yesjm
    password: yesjm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        time_zone: UTC
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always # ?? ?? ??? ??? ????, ??? ???? ????, ?? ??? ?? ???